name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nim-version:
          - 'stable'
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: "npm install node-gyp -g"
      - run: "npm install cmake-js -g"
      - run: "choosenim show path -y"
      - run: nimble install -Y
      - run: nimble test
      - run: "denim build tests/myaddon.nim -r -y --cmake"
